<?xml version="1.0"?>
<package format="3">
  <name>dynpick_driver</name>
  <version>0.2.0</version>
  <description>Driver package for Wacohtech dynpick force sensor. This contains <a href="http://ros.org/">ROS</a>-compatible linux driver, as well as a communication test tool.<br />
  As of Oct 2016, it's tested with the following models of dynpick:
  <ul>
    <li><a href="http://www.wacoh-tech.com/products/dynpick/wdf-6m200-3.html">wdf-6m200-3</a></li>
    <li><a href="http://www.wacoh-tech.com/en/products/dynpick/200n.html">WEF-6A200</a> (confirmed <a href="https://github.com/tork-a/dynpick_driver/pull/35#issuecomment-256031851">here</a>)</li>
  </ul>
  </description>

  <author email="kei.okada@gmail.com">Kei Okada</author>
  <maintainer email="dev@opensource-robotics.tokyo.jp">TORK</maintainer>

  <license>BSD</license>
  <license>GPLv2</license>
  <license>Creative Commons Attribution 4.0 International Public License (CC BY 4.0)</license>

  <url type="website">http://wiki.ros.org/dynpick_driver</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>rclcpp</depend>
  <depend>std_srvs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>rviz2</depend>
  <depend>xacro</depend>

  <test_depend>ament_cmake_test</test_depend>
  <test_depend>launch_testing</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
